"""Create bills table

Revision ID: 12a488ebad1e
Revises: f443ac42e864
Create Date: 2025-07-05 07:54:44.049595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a488ebad1e'
down_revision = 'f443ac42e864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('email_id', sa.String(length=450), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bill_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('bill_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['linked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    # ### end Alembic commands ###
