"""empty message

Revision ID: 2a6830b2df5a
Revises: ca4ea575996e
Create Date: 2024-02-15 14:13:21.669557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6830b2df5a'
down_revision = 'ca4ea575996e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('email_from', sa.String(length=150), nullable=False),
    sa.Column('email_subject', sa.String(length=150), nullable=False),
    sa.Column('attachment_password', sa.String(length=50), nullable=False),
    sa.Column('destination_folder', sa.String(length=150), nullable=True),
    sa.Column('destination_account_id', sa.UUID(), nullable=True),
    sa.Column('last_update_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['linked_accounts.id'], ),
    sa.ForeignKeyConstraint(['destination_account_id'], ['linked_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox_rules')
    # ### end Alembic commands ###
