"""empty message

Revision ID: 7dc82f7cc2ba
Revises: 2a6830b2df5a
Create Date: 2024-02-22 16:15:47.095650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc82f7cc2ba'
down_revision = '2a6830b2df5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_folder_id', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('destination_folder_name', sa.String(length=150), nullable=True))
        batch_op.drop_column('destination_folder')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_folder', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_column('destination_folder_name')
        batch_op.drop_column('destination_folder_id')

    # ### end Alembic commands ###
