"""empty message

Revision ID: f443ac42e864
Revises: 531480a39842
Create Date: 2024-05-01 18:44:43.097032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f443ac42e864'
down_revision = '531480a39842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.String(length=450), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['linked_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_emails')
    # ### end Alembic commands ###
